<a href="https://colab.research.google.com/github/yerlyn-choez/practica-rnap/blob/main/practica_rnap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **APRENDIZAJE PROFUNDO Y REFORZADO**

**NOMBRE: CHOEZ PAREDES YERLYN ALEXI**

**PRACTICAS**

**EJERCICIO PRACTICO #1 - EN CLASE**

**EJERCICIO PARCTICO #2 - EN CLASE**

**EJERCICIO PRACTICO #3 - DE TAREA**

**EJERCICIO PRACTICO #4 - DE TAREA**

# **EJERCICIO PRACTICO #1**

**Neurona**

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivada(x):
      s = sigmoid(x)
      return s * (1 - s)

In [ ]:
class Neurona:
  def __init__(self, n_entradas, lr=0.5):
      self.w = np.random.randn(n_entradas) * 0.5
      self.b = 0.0
      self.lr = lr

  def forward(self, x):
      self.x = x
      self.z = np.dot(self.w, x) + self.b
      self.a = sigmoid(self.z)
      return self.a

  def backward(self, y_real):
      error = self.a - y_real
      dz = error * sigmoid_derivada(self.z)

      dw = dz * self.x
      db = dz

      self.w -= self.lr * dw
      self.b -= self.lr * db
      return error


In [ ]:
x = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0, 1, 1, 1])


In [ ]:
x.shape

(4, 2)

In [ ]:
y.shape

(4,)

In [ ]:
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
y

array([0, 1, 1, 1])

In [ ]:
y.reshape(-1,1)

array([[0],
       [1],
       [1],
       [1]])

In [ ]:
neurona = Neurona(n_entradas = 2, lr = 5.0)

In [ ]:
for epoca in range(1000):
  error_total = 0
  for i in range(len(x)):
     salida = neurona.forward(x[i])
     error = neurona.backward(y[i])
     error_total = error_total + (error)
  if epoca % 200 == 0:
    print("epoca", epoca)
    print("error total", error_total)


epoca 0
error total -0.9178522117283814
epoca 200
error total -0.013498334799156617
epoca 400
error total -0.009520988159099263
epoca 600
error total -0.007759627102283267
epoca 800
error total -0.006711205823050917


In [ ]:
for i in range (len(x)):
  pred = neurona.forward(x[i])
  print(pred)

0.023204534967121396
0.9854470810440636
0.9854173576706712
0.9999948084170271


# **EJERCICIO PRACTICO #2**

**MLP**

In [ ]:
# Librería fundamental para cálculos numéricos y
# manejo eficiente de matrices y vectores (base de la red neuronal)
import numpy as np

In [ ]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivada(x):
    s = sigmoid(x)
    return s * (1 - s)

In [ ]:
class MLP:
    def __init__(self, n_capas, lr=1.0):
        self.lr = lr
        self.W = []
        self.b = []

        for i in range(len(n_capas) - 1):
            w = np.random.randn(n_capas[i], n_capas[i + 1]) * np.sqrt(2.0 / n_capas[i])
            b = np.zeros((1, n_capas[i + 1]))
            self.W.append(w)
            self.b.append(b)

    def forward(self, X):
        self.A = [X]
        self.Z = []
        entrada = X
        for i in range(len(self.W)):
            z = np.dot(entrada, self.W[i]) + self.b[i]
            a = sigmoid(z)

            self.Z.append(z)
            self.A.append(a)
            entrada = a
        return entrada

    def backward(self, y_real):
        m = y_real.shape[0]
        delta = (self.A[-1] - y_real) * sigmoid_derivada(self.Z[-1])

        for i in range(len(self.W) - 1, -1, -1):
            dw = np.dot(self.A[i].T, delta) / m
            db = np.sum(delta, axis = 0, keepdims = True) / m
            if i > 0:
                delta = np.dot(delta, self.W[i].T) * sigmoid_derivada(self.Z[i - 1])

            self.W[i] -= self.lr * dw
            self.b[i] -= self.lr * db


    def entrenamiento(self, X, y, epocas=5000):
        for ep in range(epocas):
            salida = self.forward(X)
            self.backward(y)

            if ep % 200 == 0:
                print("Epoca", ep)
                print("Error total", np.mean(salida - y) ** 2)





In [ ]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0, 1, 1, 1])


In [ ]:
y = y.reshape(-1, 1)

In [ ]:
np.random.seed(42)
red = MLP (n_capas = [2, 4, 1], lr = 2.0)
red.entrenamiento(X, y, epocas = 1000)

Epoca 0
Error total 0.13478444814457935
Epoca 200
Error total 0.0003785288921295248
Epoca 400
Error total 8.081264652776764e-05
Epoca 600
Error total 3.7893104722362575e-05
Epoca 800
Error total 2.345577879723753e-05


In [ ]:
predicciones = red.forward(X)
for i in range(len(X)):
    print(predicciones [i] [0])

0.053153361446572935
0.9686173213862382
0.9663164121734338
0.9956270020504066


# **EJERCICIO PRACTICO #3**

**Implementar el algoritmo del perceptrón original de Rosenblatt (con función escalón como activación) para aprender la compuerta AND. Mostrar la evolución de los pesos en cada época, verificar la convergencia y calcular la ecuación de la frontera de decisión final**

In [ ]:
# Librería fundamental para cálculos numéricos y
# manejo eficiente de matrices y vectores (base de la red neuronal)
import numpy as np

In [ ]:
# funcion ascalon
# funcion de activacion que es binaria propia del perceptron que
# convierte la salida lineal en una decision discreta  o sea una clasificacion.
def escalon(z):
  return 1 if z>= 0 else 0

In [ ]:
# clase preceptron
class Perceptron:
  def __init__(self, n_entradas, lr = 0.1):
    #se inicializan los pesos en cero porque el problema AND
    self.w = np.zeros(n_entradas)
    self.b = 0
    # learning rate: permite ajustes estables sin saltos bruscos
    self.lr = lr

  def predecir(self, x):
    #  modelo lineal: combinación ponderada de entradas + sesgo
    z = np.dot(self.w, x) + self.b
    return escalon(z)


  def entrenar(self, X, y, epocas = 10):
     # numero bajo de epocas: el perceptrón converge rapido
     # en problemas linealmente separables como AND
    for epoca in range(epocas):
      error_total = 0
      print("Epoca", epoca )

      for i in range(len(X)):
          y_pred = self.predecir(X[i])
          error = y[i] - y_pred

          # la regla de actualizacion de Rosenblatt lo que hace es
          # ajusta los pesos solo si hay error de clasificacion
          self.w += self.lr * error * X[i]
          self.b += self.lr * error

          error_total += abs(error)

     # seguimiento del proceso de aprendizaje
      print("pesos:", self.w)
      print("bias:", self.b)
      print("error total:", error_total)

      # si n llega a aparecer errores, el modelo ya separa correctamente las clases
      if error_total == 0:
        print("epoca",  epoca + 1)
        break



In [ ]:

# los datos AND
# compuerta logica AND que es linealmente separable
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0, 0, 0, 1])

In [ ]:
# entrenamiento
perceptron = Perceptron(n_entradas = 2, lr = 0.1)
perceptron.entrenar(X, y, epocas = 20)

Epoca 0
pesos: [0.1 0.1]
bias: 0.0
error total: 2
Epoca 1
pesos: [0.2 0.1]
bias: -0.1
error total: 3
Epoca 2
pesos: [0.2 0.1]
bias: -0.20000000000000004
error total: 3
Epoca 3
pesos: [0.2 0.1]
bias: -0.20000000000000004
error total: 0
epoca 4


In [ ]:
# predicciones
print("ultimas predicciones:")
for i in range(len(X)):
  print(X[i], perceptron.predecir(X[i]))

ultimas predicciones:
[0 0] 0
[0 1] 0
[1 0] 0
[1 1] 1


In [ ]:
# la ecuacion define la recta que separa las clases en el plano:
# w1*x1 + w2*x2 + b = 0
print("frontera de decision:")
print(f"{perceptron.w[0]}*x1 + {perceptron.w[1]}*x2 + {perceptron.b} = 0")

frontera de decision:
0.2*x1 + 0.1*x2 + -0.20000000000000004 = 0


# **EJERCICIO PRACTICO #4**

**Construir una red neuronal multicapa completa que clasifique las tres especies del dataset Iris. Incluir: normalización de datos, ReLU en capas ocultas, softmax en la salida, entrenamiento con cross-entropy y evaluación con accuracy. Y esta debe contener la función def predecir(self, X): return np.argmax(self.forward(X), axis=1)**

In [ ]:
# Librería fundamental para cálculos numéricos y
# manejo eficiente de matrices y vectores (base de la red neuronal)
import numpy as np

In [ ]:
# Permite acceder a datasets predefinidos como Iris, facilitando la
# carga de datos para entrenamiento y pruebas
from sklearn import datasets

In [ ]:
# Herramienta para normalizar los datos (media 0, desviación estándar 1),
# lo que mejora la estabilidad y velocidad del entrenamiento
from sklearn.preprocessing import StandardScaler

In [ ]:
# Función para dividir el dataset en conjuntos de entrenamiento y
# prueba, permitiendo evaluar el rendimiento del modelo
from sklearn.model_selection import train_test_split

In [ ]:
#  funciones de activacion

# relu: elegida para capas ocultas por su eficiencia computacional
# y porque reduce el problema del desvanecimiento del gradiente
def relu(x):
    return np.maximum(0, x)

def relu_derivada(x):
    return (x > 0).astype(float)

# softmax: transforma la salida en probabilidades para clasificación multiclase
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis = 1, keepdims  = True))
    return exp_x / np.sum(exp_x, axis = 1, keepdims = True)


In [ ]:

# red neuronal MLP
class MLP:
    def __init__(self, capas, lr=0.01):
        self.lr = lr
        self.W = []
        self.b = []

        # inicializacion He: adecuada para redes con relu
        # lo  que hace que mejore la estabilidad del entrenamient
        for i in range(len(capas) - 1):
            self.W.append(np.random.randn(capas[i], capas[i+1]) * np.sqrt(2.0 / capas[i]))
            self.b.append(np.zeros((1, capas[i+1])))

    def forward(self, X):
        self.A = [X]
        self.Z = []

        # propagacion hacia adelante en capas ocultas
        for i in range(len(self.W) - 1):
            z = np.dot(self.A[-1], self.W[i]) + self.b[i]
            a = relu(z)
            self.Z.append(z)
            self.A.append(a)

        # capa de salida con Softmax (probabilidades por clase)
        z = np.dot(self.A[-1], self.W[-1]) + self.b[-1]
        a = softmax(z)

        self.Z.append(z)
        self.A.append(a)
        return a

    def backward(self, y_onehot):
        m = y_onehot.shape[0]
        # gradiente simplificado o dereivada combinada para softmax + cross-entropy
        delta = self.A[-1] - y_onehot

        for i in range(len(self.W)-1, -1, -1):
            dw = np.dot(self.A[i].T, delta) / m
            db = np.sum(delta, axis=0, keepdims=True) / m

            # retropropagacion del error a capas anteriores
            if i > 0:
                delta = np.dot(delta, self.W[i].T) * relu_derivada(self.Z[i-1])

            self.W[i] -= self.lr * dw
            self.b[i] -= self.lr * db

    def entrenar(self, X, y_onehot, epocas=1000):
       # se usan mas épocas porque es un problema multiclase con mayor complejidad
        for ep in range(epocas):
            salida = self.forward(X)
            self.backward(y_onehot)

            if ep % 100 == 0:
              # funcion de perdida: cross-entropy
                loss = -np.mean(np.sum(y_onehot * np.log(salida + 1e-8), axis=1))
                print("Epoca", ep, "Loss:", loss)

    def predecir(self, X):
       # selecciona la clase con mayor probabilidad
        return np.argmax(self.forward(X), axis=1)



In [ ]:
# carga y preprocesamiento

# dataset iris: 3 clases de flores con 4 caracteristicas
iris = datasets.load_iris()
X = iris.data
y = iris.target

# normalizacion: mejora la convergencia del entrenamiento
scaler = StandardScaler()
X = scaler.fit_transform(X)

# codificación one-hot: necesaria para usar softmax + cross-entropy
y_onehot = np.zeros((y.size, 3))
y_onehot[np.arange(y.size), y] = 1

# separacion en entrenamiento y prueba
X_train, X_test, y_train, y_test, y_train_oh, y_test_oh = train_test_split(
    X, y, y_onehot, test_size=0.2, random_state=42)

In [ ]:

# entrenamiento
np.random.seed(42)
# arquitectura para Iris
red = MLP([4, 8, 3], lr=0.01)
red.entrenar(X_train, y_train_oh, epocas=1000)

Epoca 0 Loss: 1.5354953604521666
Epoca 100 Loss: 0.9133188493542637
Epoca 200 Loss: 0.6752030385350984
Epoca 300 Loss: 0.5261397831982467
Epoca 400 Loss: 0.4377398544426124
Epoca 500 Loss: 0.38609882314636756
Epoca 600 Loss: 0.35175240434887517
Epoca 700 Loss: 0.32588351858076137
Epoca 800 Loss: 0.30537057169674786
Epoca 900 Loss: 0.2881913259047647


In [ ]:

# evaluacion
# accuracy: proporcion de predicciones correctas
y_pred = red.predecir(X_test)
accuracy = np.mean(y_pred == y_test)
print("\nAccuracy:", accuracy)


Accuracy: 0.9
